import { SavedView } from "./views.types";

const nowIso = () => new Date().toISOString();

const baseColumns = [
  "priority",
  "status",
  "epic",
  "name",
  "externalOwner",
  "nextFollowUpAt",
  "overdue",
  "impact",
  "financialMonthly",
  "financialOneOff",
  "escalateTo",
];

export const DEMAND_DEFAULT_VIEWS: SavedView[] = [
  {
    id: "v_overdue",
    scope: "demands",
    name: "Atrasados (Overdue)",
    description: "Tudo que está Aguardando terceiros e com follow-up vencido.",
    filters: [{ field: "overdue", op: "eq", value: true }],
    sort: [
      { field: "priority", dir: "asc" },
      { field: "nextFollowUpAt", dir: "asc" },
      { field: "impact", dir: "desc" },
    ],
    columns: baseColumns,
    isPinned: true,
    isDefault: true,
    updatedAt: nowIso(),
  },
  {
    id: "v_today",
    scope: "demands",
    name: "Hoje",
    description: "Follow-ups agendados para hoje.",
    filters: [
      { field: "nextFollowUpAt", op: "today" },
      { field: "status", op: "ne", value: "Concluído" },
      { field: "status", op: "ne", value: "Cancelado" },
    ],
    sort: [
      { field: "priority", dir: "asc" },
      { field: "impact", dir: "desc" },
    ],
    columns: baseColumns,
    isPinned: true,
    isDefault: true,
    updatedAt: nowIso(),
  },
  {
    id: "v_no_next",
    scope: "demands",
    name: "Sem próximo follow-up",
    description: "Itens sem nextFollowUpAt definido (risco de esquecimento).",
    filters: [
      { field: "nextFollowUpAt", op: "isnull" },
      {
        field: "status",
        op: "in",
        value: ["Backlog", "Esta semana", "Em execução", "Aguardando terceiros"],
      },
    ],
    sort: [
      { field: "priority", dir: "asc" },
      { field: "createdAt", dir: "asc" },
    ],
    columns: baseColumns,
    isPinned: true,
    isDefault: true,
    updatedAt: nowIso(),
  },
  {
    id: "v_waiting",
    scope: "demands",
    name: "Aguardando terceiros",
    description: "Fila de cobrança/depêndencias externas.",
    filters: [{ field: "status", op: "eq", value: "Aguardando terceiros" }],
    sort: [
      { field: "priority", dir: "asc" },
      { field: "nextFollowUpAt", dir: "asc" },
    ],
    columns: baseColumns,
    isPinned: true,
    isDefault: true,
    updatedAt: nowIso(),
  },
  {
    id: "v_p0",
    scope: "demands",
    name: "P0 War Room",
    description: "Tudo que é P0 (aberto) com foco em desbloqueio e escalonamento.",
    filters: [
      { field: "priority", op: "eq", value: "P0" },
      { field: "status", op: "ne", value: "Concluído" },
      { field: "status", op: "ne", value: "Cancelado" },
    ],
    sort: [
      { field: "overdue", dir: "desc" },
      { field: "status", dir: "asc" },
      { field: "nextFollowUpAt", dir: "asc" },
    ],
    columns: baseColumns,
    isPinned: true,
    isDefault: true,
    updatedAt: nowIso(),
  },
];

export const TICKET_DEFAULT_VIEWS: SavedView[] = [
  {
    id: "t_open",
    scope: "tickets",
    name: "Abertos",
    description: "Chamados abertos.",
    filters: [{ field: "status", op: "ne", value: "Fechado" }],
    sort: [{ field: "openedAt", dir: "asc" }],
    columns: ["slaDueAt", "subject", "queue", "status", "priority", "openedAt", "channel"],
    isPinned: true,
    isDefault: true,
    updatedAt: nowIso(),
  },
  {
    id: "t_sla_risk",
    scope: "tickets",
    name: "Risco de SLA (48h)",
    description: "SLA vence nas próximas 48h.",
    filters: [{ field: "isSlaRisk", op: "eq", value: true }],
    sort: [{ field: "slaDueAt", dir: "asc" }],
    columns: ["slaDueAt", "subject", "queue", "status", "priority", "channel"],
    isPinned: true,
    isDefault: true,
    updatedAt: nowIso(),
  },
  {
    id: "t_overdue",
    scope: "tickets",
    name: "SLA estourado",
    description: "Chamados com SLA vencido.",
    filters: [{ field: "isSlaOverdue", op: "eq", value: true }],
    sort: [{ field: "slaDueAt", dir: "asc" }],
    columns: ["slaDueAt", "subject", "queue", "status", "priority", "channel"],
    isPinned: true,
    isDefault: true,
    updatedAt: nowIso(),
  },
  {
    id: "t_by_system_sankhya",
    scope: "tickets",
    name: "Sankhya",
    description: "Chamados do sistema Sankhya.",
    filters: [{ field: "system", op: "eq", value: "Sankhya" }],
    sort: [{ field: "openedAt", dir: "asc" }],
    columns: ["slaDueAt", "subject", "queue", "status", "priority", "openedAt", "channel"],
    isPinned: true,
    isDefault: true,
    updatedAt: nowIso(),
  },
  {
    id: "t_unlinked",
    scope: "tickets",
    name: "Sem vínculo",
    description: "Chamados sem demanda vinculada.",
    filters: [{ field: "demandId", op: "isnull" }],
    sort: [{ field: "openedAt", dir: "asc" }],
    columns: ["slaDueAt", "subject", "queue", "status", "priority", "openedAt", "channel"],
    isPinned: true,
    isDefault: true,
    updatedAt: nowIso(),
  },
];
